/****** Object:  Database [SantanderChalenge]    Script Date: 15/3/2020 14:53:54 ******/
CREATE DATABASE [SantanderChalenge]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SantanderChalenge', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SantanderChalenge.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SantanderChalenge_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SantanderChalenge_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SantanderChalenge].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SantanderChalenge] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SantanderChalenge] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SantanderChalenge] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SantanderChalenge] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SantanderChalenge] SET ARITHABORT OFF 
GO

ALTER DATABASE [SantanderChalenge] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SantanderChalenge] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SantanderChalenge] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SantanderChalenge] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SantanderChalenge] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SantanderChalenge] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SantanderChalenge] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SantanderChalenge] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SantanderChalenge] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SantanderChalenge] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SantanderChalenge] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SantanderChalenge] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SantanderChalenge] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SantanderChalenge] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SantanderChalenge] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SantanderChalenge] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SantanderChalenge] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SantanderChalenge] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SantanderChalenge] SET  MULTI_USER 
GO

ALTER DATABASE [SantanderChalenge] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SantanderChalenge] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SantanderChalenge] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SantanderChalenge] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SantanderChalenge] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SantanderChalenge] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SantanderChalenge] SET  READ_WRITE 
GO


