CREATE TABLE [MEETUPS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[user_organizer] [int] NOT NULL,
	[title] [varchar](150) NOT NULL,
	[canceled] [int] NOT NULL,
	[date] [datetime] NOT NULL,
	[guests] [int] NOT NULL,
 CONSTRAINT [PK_MEETUPS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


